services:
  - type: web
    name: pythonsquad
    runtime: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT backend.app:app"
    envVars:
      - key: MONGO_URI
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_DEFAULT_SENDER
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 10000
